// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: world_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmicScavengers.Networking.Protobuf.WorldData {

  /// <summary>Holder for reflection information generated from world_data.proto</summary>
  public static partial class WorldDataReflection {

    #region Descriptor
    /// <summary>File descriptor for world_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChB3b3JsZF9kYXRhLnByb3RvEi5Db3NtaWNTY2F2ZW5nZXJzLk5ldHdvcmtp",
            "bmcuUHJvdG9idWYuV29ybGREYXRhIngKCVdvcmxkRGF0YRIKCgJpZBgBIAEo",
            "AxISCgp3b3JsZF9uYW1lGAIgASgJEhAKCG1hcF9zZWVkGAMgASgDEhkKEXNl",
            "Y3Rvcl9zaXplX3VuaXRzGAQgASgFEh4KFmdlbmVyYXRpb25fY29uZmlnX2pz",
            "b24YBSABKAliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.WorldData.WorldData), global::CosmicScavengers.Networking.Protobuf.WorldData.WorldData.Parser, new[]{ "Id", "WorldName", "MapSeed", "SectorSizeUnits", "GenerationConfigJson" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Mirrors the jOOQ Worlds POJO for network transmission.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorldData : pb::IMessage<WorldData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorldData> _parser = new pb::MessageParser<WorldData>(() => new WorldData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorldData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.WorldData.WorldDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldData(WorldData other) : this() {
      id_ = other.id_;
      worldName_ = other.worldName_;
      mapSeed_ = other.mapSeed_;
      sectorSizeUnits_ = other.sectorSizeUnits_;
      generationConfigJson_ = other.generationConfigJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorldData Clone() {
      return new WorldData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// Database primary key ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "world_name" field.</summary>
    public const int WorldNameFieldNumber = 2;
    private string worldName_ = "";
    /// <summary>
    /// Name of the world (String)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorldName {
      get { return worldName_; }
      set {
        worldName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "map_seed" field.</summary>
    public const int MapSeedFieldNumber = 3;
    private long mapSeed_;
    /// <summary>
    /// Seed used for map generation (Long)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MapSeed {
      get { return mapSeed_; }
      set {
        mapSeed_ = value;
      }
    }

    /// <summary>Field number for the "sector_size_units" field.</summary>
    public const int SectorSizeUnitsFieldNumber = 4;
    private int sectorSizeUnits_;
    /// <summary>
    /// Size of a sector in game units (Integer)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SectorSizeUnits {
      get { return sectorSizeUnits_; }
      set {
        sectorSizeUnits_ = value;
      }
    }

    /// <summary>Field number for the "generation_config_json" field.</summary>
    public const int GenerationConfigJsonFieldNumber = 5;
    private string generationConfigJson_ = "";
    /// <summary>
    /// The JSONB generation configuration, serialized as a raw JSON string.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GenerationConfigJson {
      get { return generationConfigJson_; }
      set {
        generationConfigJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorldData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorldData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (WorldName != other.WorldName) return false;
      if (MapSeed != other.MapSeed) return false;
      if (SectorSizeUnits != other.SectorSizeUnits) return false;
      if (GenerationConfigJson != other.GenerationConfigJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (WorldName.Length != 0) hash ^= WorldName.GetHashCode();
      if (MapSeed != 0L) hash ^= MapSeed.GetHashCode();
      if (SectorSizeUnits != 0) hash ^= SectorSizeUnits.GetHashCode();
      if (GenerationConfigJson.Length != 0) hash ^= GenerationConfigJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (WorldName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorldName);
      }
      if (MapSeed != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MapSeed);
      }
      if (SectorSizeUnits != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SectorSizeUnits);
      }
      if (GenerationConfigJson.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GenerationConfigJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (WorldName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(WorldName);
      }
      if (MapSeed != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MapSeed);
      }
      if (SectorSizeUnits != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SectorSizeUnits);
      }
      if (GenerationConfigJson.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GenerationConfigJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (WorldName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorldName);
      }
      if (MapSeed != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MapSeed);
      }
      if (SectorSizeUnits != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SectorSizeUnits);
      }
      if (GenerationConfigJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GenerationConfigJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorldData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.WorldName.Length != 0) {
        WorldName = other.WorldName;
      }
      if (other.MapSeed != 0L) {
        MapSeed = other.MapSeed;
      }
      if (other.SectorSizeUnits != 0) {
        SectorSizeUnits = other.SectorSizeUnits;
      }
      if (other.GenerationConfigJson.Length != 0) {
        GenerationConfigJson = other.GenerationConfigJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            WorldName = input.ReadString();
            break;
          }
          case 24: {
            MapSeed = input.ReadInt64();
            break;
          }
          case 32: {
            SectorSizeUnits = input.ReadInt32();
            break;
          }
          case 42: {
            GenerationConfigJson = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            WorldName = input.ReadString();
            break;
          }
          case 24: {
            MapSeed = input.ReadInt64();
            break;
          }
          case 32: {
            SectorSizeUnits = input.ReadInt32();
            break;
          }
          case 42: {
            GenerationConfigJson = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
