// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: traits.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmicScavengers.Networking.Protobuf.Traits {

  /// <summary>Holder for reflection information generated from traits.proto</summary>
  public static partial class TraitsReflection {

    #region Descriptor
    /// <summary>File descriptor for traits.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TraitsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgx0cmFpdHMucHJvdG8SGGNvc21pY19zY2F2ZW5nZXJzLnRyYWl0cxoZZ29v",
            "Z2xlL3Byb3RvYnVmL2FueS5wcm90byJHCg9Nb3ZlVGFyZ2V0UHJvdG8SEAoI",
            "dGFyZ2V0X3gYASABKBASEAoIdGFyZ2V0X3kYAiABKBASEAoIdGFyZ2V0X3oY",
            "AyABKBAiWwoUU2VsZWN0YWJsZVRyYWl0UHJvdG8SEAoIcHJpb3JpdHkYASAB",
            "KAUSGAoQc2VsZWN0aW9uX3JhZGl1cxgCIAEoEBIXCg9zaG93X2hlYWx0aF9i",
            "YXIYAyABKAgiigIKEU1vdmFibGVUcmFpdFByb3RvEhAKCHByaW9yaXR5GAEg",
            "ASgFEkIKBnN0YXR1cxgCIAEoDjIyLmNvc21pY19zY2F2ZW5nZXJzLnRyYWl0",
            "cy5Nb3ZhYmxlVHJhaXRQcm90by5TdGF0dXMSEAoIdGFyZ2V0X3gYAyABKBAS",
            "EAoIdGFyZ2V0X3kYBCABKBASEAoIdGFyZ2V0X3oYBSABKBASFgoObW92ZW1l",
            "bnRfc3BlZWQYBiABKBASFgoOcm90YXRpb25fc3BlZWQYByABKBASGQoRc3Rv",
            "cHBpbmdfZGlzdGFuY2UYCCABKBAiHgoGU3RhdHVzEggKBElETEUQABIKCgZN",
            "T1ZJTkcQASJKChJUcmFpdEluc3RhbmNlUHJvdG8SEAoIdHJhaXRfaWQYASAB",
            "KAkSIgoEZGF0YRgCIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkiawoRRW50",
            "aXR5VHJhaXRzUHJvdG8SEQoJZW50aXR5X2lkGAEgASgDEkMKDWFjdGl2ZV90",
            "cmFpdHMYAiADKAsyLC5jb3NtaWNfc2NhdmVuZ2Vycy50cmFpdHMuVHJhaXRJ",
            "bnN0YW5jZVByb3RvImUKD01vdmVJbnRlbnRQcm90bxIRCgllbnRpdHlfaWQY",
            "ASABKAMSPwoMcmVxdWVzdF9kYXRhGAIgASgLMikuY29zbWljX3NjYXZlbmdl",
            "cnMudHJhaXRzLk1vdmVUYXJnZXRQcm90b0JfCi1jb20uY29zbWljLnNjYXZl",
            "bmdlcnMubmV0d29ya2luZy5wcm90by50cmFpdHNQAaoCK0Nvc21pY1NjYXZl",
            "bmdlcnMuTmV0d29ya2luZy5Qcm90b2J1Zi5UcmFpdHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto), global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto.Parser, new[]{ "TargetX", "TargetY", "TargetZ" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.SelectableTraitProto), global::CosmicScavengers.Networking.Protobuf.Traits.SelectableTraitProto.Parser, new[]{ "Priority", "SelectionRadius", "ShowHealthBar" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto), global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Parser, new[]{ "Priority", "Status", "TargetX", "TargetY", "TargetZ", "MovementSpeed", "RotationSpeed", "StoppingDistance" }, null, new[]{ typeof(global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto), global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto.Parser, new[]{ "TraitId", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.EntityTraitsProto), global::CosmicScavengers.Networking.Protobuf.Traits.EntityTraitsProto.Parser, new[]{ "EntityId", "ActiveTraits" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Traits.MoveIntentProto), global::CosmicScavengers.Networking.Protobuf.Traits.MoveIntentProto.Parser, new[]{ "EntityId", "RequestData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Reusable coordinate and movement data to ensure 
  /// consistency between Intent and State.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MoveTargetProto : pb::IMessage<MoveTargetProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveTargetProto> _parser = new pb::MessageParser<MoveTargetProto>(() => new MoveTargetProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveTargetProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveTargetProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveTargetProto(MoveTargetProto other) : this() {
      targetX_ = other.targetX_;
      targetY_ = other.targetY_;
      targetZ_ = other.targetZ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveTargetProto Clone() {
      return new MoveTargetProto(this);
    }

    /// <summary>Field number for the "target_x" field.</summary>
    public const int TargetXFieldNumber = 1;
    private long targetX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetX {
      get { return targetX_; }
      set {
        targetX_ = value;
      }
    }

    /// <summary>Field number for the "target_y" field.</summary>
    public const int TargetYFieldNumber = 2;
    private long targetY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetY {
      get { return targetY_; }
      set {
        targetY_ = value;
      }
    }

    /// <summary>Field number for the "target_z" field.</summary>
    public const int TargetZFieldNumber = 3;
    private long targetZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetZ {
      get { return targetZ_; }
      set {
        targetZ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveTargetProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveTargetProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetX != other.TargetX) return false;
      if (TargetY != other.TargetY) return false;
      if (TargetZ != other.TargetZ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetX != 0L) hash ^= TargetX.GetHashCode();
      if (TargetY != 0L) hash ^= TargetY.GetHashCode();
      if (TargetZ != 0L) hash ^= TargetZ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TargetX != 0L) {
        output.WriteRawTag(9);
        output.WriteSFixed64(TargetX);
      }
      if (TargetY != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(TargetY);
      }
      if (TargetZ != 0L) {
        output.WriteRawTag(25);
        output.WriteSFixed64(TargetZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TargetX != 0L) {
        output.WriteRawTag(9);
        output.WriteSFixed64(TargetX);
      }
      if (TargetY != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(TargetY);
      }
      if (TargetZ != 0L) {
        output.WriteRawTag(25);
        output.WriteSFixed64(TargetZ);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TargetX != 0L) {
        size += 1 + 8;
      }
      if (TargetY != 0L) {
        size += 1 + 8;
      }
      if (TargetZ != 0L) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveTargetProto other) {
      if (other == null) {
        return;
      }
      if (other.TargetX != 0L) {
        TargetX = other.TargetX;
      }
      if (other.TargetY != 0L) {
        TargetY = other.TargetY;
      }
      if (other.TargetZ != 0L) {
        TargetZ = other.TargetZ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TargetX = input.ReadSFixed64();
            break;
          }
          case 17: {
            TargetY = input.ReadSFixed64();
            break;
          }
          case 25: {
            TargetZ = input.ReadSFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TargetX = input.ReadSFixed64();
            break;
          }
          case 17: {
            TargetY = input.ReadSFixed64();
            break;
          }
          case 25: {
            TargetZ = input.ReadSFixed64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// SELECTABLE: Defines how a player interacts with the entity via UI/Mouse
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SelectableTraitProto : pb::IMessage<SelectableTraitProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SelectableTraitProto> _parser = new pb::MessageParser<SelectableTraitProto>(() => new SelectableTraitProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SelectableTraitProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectableTraitProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectableTraitProto(SelectableTraitProto other) : this() {
      priority_ = other.priority_;
      selectionRadius_ = other.selectionRadius_;
      showHealthBar_ = other.showHealthBar_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectableTraitProto Clone() {
      return new SelectableTraitProto(this);
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 1;
    private int priority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Priority {
      get { return priority_; }
      set {
        priority_ = value;
      }
    }

    /// <summary>Field number for the "selection_radius" field.</summary>
    public const int SelectionRadiusFieldNumber = 2;
    private long selectionRadius_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SelectionRadius {
      get { return selectionRadius_; }
      set {
        selectionRadius_ = value;
      }
    }

    /// <summary>Field number for the "show_health_bar" field.</summary>
    public const int ShowHealthBarFieldNumber = 3;
    private bool showHealthBar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ShowHealthBar {
      get { return showHealthBar_; }
      set {
        showHealthBar_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SelectableTraitProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SelectableTraitProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Priority != other.Priority) return false;
      if (SelectionRadius != other.SelectionRadius) return false;
      if (ShowHealthBar != other.ShowHealthBar) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Priority != 0) hash ^= Priority.GetHashCode();
      if (SelectionRadius != 0L) hash ^= SelectionRadius.GetHashCode();
      if (ShowHealthBar != false) hash ^= ShowHealthBar.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Priority != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Priority);
      }
      if (SelectionRadius != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(SelectionRadius);
      }
      if (ShowHealthBar != false) {
        output.WriteRawTag(24);
        output.WriteBool(ShowHealthBar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Priority != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Priority);
      }
      if (SelectionRadius != 0L) {
        output.WriteRawTag(17);
        output.WriteSFixed64(SelectionRadius);
      }
      if (ShowHealthBar != false) {
        output.WriteRawTag(24);
        output.WriteBool(ShowHealthBar);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Priority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Priority);
      }
      if (SelectionRadius != 0L) {
        size += 1 + 8;
      }
      if (ShowHealthBar != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SelectableTraitProto other) {
      if (other == null) {
        return;
      }
      if (other.Priority != 0) {
        Priority = other.Priority;
      }
      if (other.SelectionRadius != 0L) {
        SelectionRadius = other.SelectionRadius;
      }
      if (other.ShowHealthBar != false) {
        ShowHealthBar = other.ShowHealthBar;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Priority = input.ReadInt32();
            break;
          }
          case 17: {
            SelectionRadius = input.ReadSFixed64();
            break;
          }
          case 24: {
            ShowHealthBar = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Priority = input.ReadInt32();
            break;
          }
          case 17: {
            SelectionRadius = input.ReadSFixed64();
            break;
          }
          case 24: {
            ShowHealthBar = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// MOVABLE: Defines the current physical state of a simulated entity
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MovableTraitProto : pb::IMessage<MovableTraitProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MovableTraitProto> _parser = new pb::MessageParser<MovableTraitProto>(() => new MovableTraitProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MovableTraitProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovableTraitProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovableTraitProto(MovableTraitProto other) : this() {
      priority_ = other.priority_;
      status_ = other.status_;
      targetX_ = other.targetX_;
      targetY_ = other.targetY_;
      targetZ_ = other.targetZ_;
      movementSpeed_ = other.movementSpeed_;
      rotationSpeed_ = other.rotationSpeed_;
      stoppingDistance_ = other.stoppingDistance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MovableTraitProto Clone() {
      return new MovableTraitProto(this);
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 1;
    private int priority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Priority {
      get { return priority_; }
      set {
        priority_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    private global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status status_ = global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "target_x" field.</summary>
    public const int TargetXFieldNumber = 3;
    private long targetX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetX {
      get { return targetX_; }
      set {
        targetX_ = value;
      }
    }

    /// <summary>Field number for the "target_y" field.</summary>
    public const int TargetYFieldNumber = 4;
    private long targetY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetY {
      get { return targetY_; }
      set {
        targetY_ = value;
      }
    }

    /// <summary>Field number for the "target_z" field.</summary>
    public const int TargetZFieldNumber = 5;
    private long targetZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetZ {
      get { return targetZ_; }
      set {
        targetZ_ = value;
      }
    }

    /// <summary>Field number for the "movement_speed" field.</summary>
    public const int MovementSpeedFieldNumber = 6;
    private long movementSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MovementSpeed {
      get { return movementSpeed_; }
      set {
        movementSpeed_ = value;
      }
    }

    /// <summary>Field number for the "rotation_speed" field.</summary>
    public const int RotationSpeedFieldNumber = 7;
    private long rotationSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RotationSpeed {
      get { return rotationSpeed_; }
      set {
        rotationSpeed_ = value;
      }
    }

    /// <summary>Field number for the "stopping_distance" field.</summary>
    public const int StoppingDistanceFieldNumber = 8;
    private long stoppingDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StoppingDistance {
      get { return stoppingDistance_; }
      set {
        stoppingDistance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MovableTraitProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MovableTraitProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Priority != other.Priority) return false;
      if (Status != other.Status) return false;
      if (TargetX != other.TargetX) return false;
      if (TargetY != other.TargetY) return false;
      if (TargetZ != other.TargetZ) return false;
      if (MovementSpeed != other.MovementSpeed) return false;
      if (RotationSpeed != other.RotationSpeed) return false;
      if (StoppingDistance != other.StoppingDistance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Priority != 0) hash ^= Priority.GetHashCode();
      if (Status != global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle) hash ^= Status.GetHashCode();
      if (TargetX != 0L) hash ^= TargetX.GetHashCode();
      if (TargetY != 0L) hash ^= TargetY.GetHashCode();
      if (TargetZ != 0L) hash ^= TargetZ.GetHashCode();
      if (MovementSpeed != 0L) hash ^= MovementSpeed.GetHashCode();
      if (RotationSpeed != 0L) hash ^= RotationSpeed.GetHashCode();
      if (StoppingDistance != 0L) hash ^= StoppingDistance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Priority != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Priority);
      }
      if (Status != global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (TargetX != 0L) {
        output.WriteRawTag(25);
        output.WriteSFixed64(TargetX);
      }
      if (TargetY != 0L) {
        output.WriteRawTag(33);
        output.WriteSFixed64(TargetY);
      }
      if (TargetZ != 0L) {
        output.WriteRawTag(41);
        output.WriteSFixed64(TargetZ);
      }
      if (MovementSpeed != 0L) {
        output.WriteRawTag(49);
        output.WriteSFixed64(MovementSpeed);
      }
      if (RotationSpeed != 0L) {
        output.WriteRawTag(57);
        output.WriteSFixed64(RotationSpeed);
      }
      if (StoppingDistance != 0L) {
        output.WriteRawTag(65);
        output.WriteSFixed64(StoppingDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Priority != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Priority);
      }
      if (Status != global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Status);
      }
      if (TargetX != 0L) {
        output.WriteRawTag(25);
        output.WriteSFixed64(TargetX);
      }
      if (TargetY != 0L) {
        output.WriteRawTag(33);
        output.WriteSFixed64(TargetY);
      }
      if (TargetZ != 0L) {
        output.WriteRawTag(41);
        output.WriteSFixed64(TargetZ);
      }
      if (MovementSpeed != 0L) {
        output.WriteRawTag(49);
        output.WriteSFixed64(MovementSpeed);
      }
      if (RotationSpeed != 0L) {
        output.WriteRawTag(57);
        output.WriteSFixed64(RotationSpeed);
      }
      if (StoppingDistance != 0L) {
        output.WriteRawTag(65);
        output.WriteSFixed64(StoppingDistance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Priority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Priority);
      }
      if (Status != global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (TargetX != 0L) {
        size += 1 + 8;
      }
      if (TargetY != 0L) {
        size += 1 + 8;
      }
      if (TargetZ != 0L) {
        size += 1 + 8;
      }
      if (MovementSpeed != 0L) {
        size += 1 + 8;
      }
      if (RotationSpeed != 0L) {
        size += 1 + 8;
      }
      if (StoppingDistance != 0L) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MovableTraitProto other) {
      if (other == null) {
        return;
      }
      if (other.Priority != 0) {
        Priority = other.Priority;
      }
      if (other.Status != global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status.Idle) {
        Status = other.Status;
      }
      if (other.TargetX != 0L) {
        TargetX = other.TargetX;
      }
      if (other.TargetY != 0L) {
        TargetY = other.TargetY;
      }
      if (other.TargetZ != 0L) {
        TargetZ = other.TargetZ;
      }
      if (other.MovementSpeed != 0L) {
        MovementSpeed = other.MovementSpeed;
      }
      if (other.RotationSpeed != 0L) {
        RotationSpeed = other.RotationSpeed;
      }
      if (other.StoppingDistance != 0L) {
        StoppingDistance = other.StoppingDistance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Priority = input.ReadInt32();
            break;
          }
          case 16: {
            Status = (global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status) input.ReadEnum();
            break;
          }
          case 25: {
            TargetX = input.ReadSFixed64();
            break;
          }
          case 33: {
            TargetY = input.ReadSFixed64();
            break;
          }
          case 41: {
            TargetZ = input.ReadSFixed64();
            break;
          }
          case 49: {
            MovementSpeed = input.ReadSFixed64();
            break;
          }
          case 57: {
            RotationSpeed = input.ReadSFixed64();
            break;
          }
          case 65: {
            StoppingDistance = input.ReadSFixed64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Priority = input.ReadInt32();
            break;
          }
          case 16: {
            Status = (global::CosmicScavengers.Networking.Protobuf.Traits.MovableTraitProto.Types.Status) input.ReadEnum();
            break;
          }
          case 25: {
            TargetX = input.ReadSFixed64();
            break;
          }
          case 33: {
            TargetY = input.ReadSFixed64();
            break;
          }
          case 41: {
            TargetZ = input.ReadSFixed64();
            break;
          }
          case 49: {
            MovementSpeed = input.ReadSFixed64();
            break;
          }
          case 57: {
            RotationSpeed = input.ReadSFixed64();
            break;
          }
          case 65: {
            StoppingDistance = input.ReadSFixed64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MovableTraitProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Status {
        [pbr::OriginalName("IDLE")] Idle = 0,
        [pbr::OriginalName("MOVING")] Moving = 1,
      }

    }
    #endregion

  }

  /// <summary>
  /// A single Trait container. Using 'oneof' allows the Unity client 
  /// to switch/case on the type of trait being received.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TraitInstanceProto : pb::IMessage<TraitInstanceProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TraitInstanceProto> _parser = new pb::MessageParser<TraitInstanceProto>(() => new TraitInstanceProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TraitInstanceProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TraitInstanceProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TraitInstanceProto(TraitInstanceProto other) : this() {
      traitId_ = other.traitId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TraitInstanceProto Clone() {
      return new TraitInstanceProto(this);
    }

    /// <summary>Field number for the "trait_id" field.</summary>
    public const int TraitIdFieldNumber = 1;
    private string traitId_ = "";
    /// <summary>
    /// String ID for fast lookup on client (e.g., "movable")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TraitId {
      get { return traitId_; }
      set {
        traitId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    /// <summary>
    /// The "Magic" container that can hold any of the messages above 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TraitInstanceProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TraitInstanceProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TraitId != other.TraitId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TraitId.Length != 0) hash ^= TraitId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TraitId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TraitId);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TraitId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TraitId);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TraitId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TraitId);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TraitInstanceProto other) {
      if (other == null) {
        return;
      }
      if (other.TraitId.Length != 0) {
        TraitId = other.TraitId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TraitId = input.ReadString();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TraitId = input.ReadString();
            break;
          }
          case 18: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The complete data packet for an entity's traits.
  /// This is what the Java Server sends to the Unity Client.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityTraitsProto : pb::IMessage<EntityTraitsProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityTraitsProto> _parser = new pb::MessageParser<EntityTraitsProto>(() => new EntityTraitsProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityTraitsProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityTraitsProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityTraitsProto(EntityTraitsProto other) : this() {
      entityId_ = other.entityId_;
      activeTraits_ = other.activeTraits_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityTraitsProto Clone() {
      return new EntityTraitsProto(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private long entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "active_traits" field.</summary>
    public const int ActiveTraitsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> _repeated_activeTraits_codec
        = pb::FieldCodec.ForMessage(18, global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> activeTraits_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> ActiveTraits {
      get { return activeTraits_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityTraitsProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityTraitsProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if(!activeTraits_.Equals(other.activeTraits_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0L) hash ^= EntityId.GetHashCode();
      hash ^= activeTraits_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(EntityId);
      }
      activeTraits_.WriteTo(output, _repeated_activeTraits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(EntityId);
      }
      activeTraits_.WriteTo(ref output, _repeated_activeTraits_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EntityId);
      }
      size += activeTraits_.CalculateSize(_repeated_activeTraits_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityTraitsProto other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0L) {
        EntityId = other.EntityId;
      }
      activeTraits_.Add(other.activeTraits_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EntityId = input.ReadInt64();
            break;
          }
          case 18: {
            activeTraits_.AddEntriesFrom(input, _repeated_activeTraits_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EntityId = input.ReadInt64();
            break;
          }
          case 18: {
            activeTraits_.AddEntriesFrom(ref input, _repeated_activeTraits_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The Request (The Intent sent from Client to Server)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MoveIntentProto : pb::IMessage<MoveIntentProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveIntentProto> _parser = new pb::MessageParser<MoveIntentProto>(() => new MoveIntentProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveIntentProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveIntentProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveIntentProto(MoveIntentProto other) : this() {
      entityId_ = other.entityId_;
      requestData_ = other.requestData_ != null ? other.requestData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveIntentProto Clone() {
      return new MoveIntentProto(this);
    }

    /// <summary>Field number for the "entity_id" field.</summary>
    public const int EntityIdFieldNumber = 1;
    private long entityId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long EntityId {
      get { return entityId_; }
      set {
        entityId_ = value;
      }
    }

    /// <summary>Field number for the "request_data" field.</summary>
    public const int RequestDataFieldNumber = 2;
    private global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto requestData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto RequestData {
      get { return requestData_; }
      set {
        requestData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveIntentProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveIntentProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntityId != other.EntityId) return false;
      if (!object.Equals(RequestData, other.RequestData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EntityId != 0L) hash ^= EntityId.GetHashCode();
      if (requestData_ != null) hash ^= RequestData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EntityId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(EntityId);
      }
      if (requestData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RequestData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EntityId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(EntityId);
      }
      if (requestData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RequestData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EntityId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(EntityId);
      }
      if (requestData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RequestData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveIntentProto other) {
      if (other == null) {
        return;
      }
      if (other.EntityId != 0L) {
        EntityId = other.EntityId;
      }
      if (other.requestData_ != null) {
        if (requestData_ == null) {
          RequestData = new global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto();
        }
        RequestData.MergeFrom(other.RequestData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EntityId = input.ReadInt64();
            break;
          }
          case 18: {
            if (requestData_ == null) {
              RequestData = new global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto();
            }
            input.ReadMessage(RequestData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EntityId = input.ReadInt64();
            break;
          }
          case 18: {
            if (requestData_ == null) {
              RequestData = new global::CosmicScavengers.Networking.Protobuf.Traits.MoveTargetProto();
            }
            input.ReadMessage(RequestData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
