// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player_entity_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmicScavengers.Networking.Protobuf.PlayerEntities {

  /// <summary>Holder for reflection information generated from player_entity_data.proto</summary>
  public static partial class PlayerEntityDataReflection {

    #region Descriptor
    /// <summary>File descriptor for player_entity_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerEntityDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhwbGF5ZXJfZW50aXR5X2RhdGEucHJvdG8SM0Nvc21pY1NjYXZlbmdlcnMu",
            "TmV0d29ya2luZy5Qcm90b2J1Zi5QbGF5ZXJFbnRpdGllcxofZ29vZ2xlL3By",
            "b3RvYnVmL3RpbWVzdGFtcC5wcm90byLCAgoQUGxheWVyRW50aXR5RGF0YRIK",
            "CgJpZBgBIAEoAxIPCgdjaHVua194GAIgASgFEg8KB2NodW5rX3kYAyABKAUS",
            "EwoLZW50aXR5X3R5cGUYBCABKAkSDgoGaGVhbHRoGAUgASgFEg0KBXBvc194",
            "GAYgASgCEg0KBXBvc195GAcgASgCEhIKCnN0YXRlX2RhdGEYCCABKAkSEQoJ",
            "cGxheWVyX2lkGAkgASgDEhAKCHdvcmxkX2lkGAogASgDEhEKCXNlY3Rvcl9p",
            "ZBgLIAEoAxIRCglpc19zdGF0aWMYDCABKAgSLgoKY3JlYXRlZF9hdBgNIAEo",
            "CzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgO",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntityData), global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntityData.Parser, new[]{ "Id", "ChunkX", "ChunkY", "EntityType", "Health", "PosX", "PosY", "StateData", "PlayerId", "WorldId", "SectorId", "IsStatic", "CreatedAt", "UpdatedAt" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Mirrors the jOOQ PlayerEntities POJO for network transmission.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerEntityData : pb::IMessage<PlayerEntityData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerEntityData> _parser = new pb::MessageParser<PlayerEntityData>(() => new PlayerEntityData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerEntityData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntityDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityData(PlayerEntityData other) : this() {
      id_ = other.id_;
      chunkX_ = other.chunkX_;
      chunkY_ = other.chunkY_;
      entityType_ = other.entityType_;
      health_ = other.health_;
      posX_ = other.posX_;
      posY_ = other.posY_;
      stateData_ = other.stateData_;
      playerId_ = other.playerId_;
      worldId_ = other.worldId_;
      sectorId_ = other.sectorId_;
      isStatic_ = other.isStatic_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityData Clone() {
      return new PlayerEntityData(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// Database primary key ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "chunk_x" field.</summary>
    public const int ChunkXFieldNumber = 2;
    private int chunkX_;
    /// <summary>
    /// Position in chunk coordinates (integer based)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkX {
      get { return chunkX_; }
      set {
        chunkX_ = value;
      }
    }

    /// <summary>Field number for the "chunk_y" field.</summary>
    public const int ChunkYFieldNumber = 3;
    private int chunkY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkY {
      get { return chunkY_; }
      set {
        chunkY_ = value;
      }
    }

    /// <summary>Field number for the "entity_type" field.</summary>
    public const int EntityTypeFieldNumber = 4;
    private string entityType_ = "";
    /// <summary>
    /// Entity type identifier (e.g., "Player", "Enemy", "ResourceNode")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityType {
      get { return entityType_; }
      set {
        entityType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "health" field.</summary>
    public const int HealthFieldNumber = 5;
    private int health_;
    /// <summary>
    /// Current health value
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Health {
      get { return health_; }
      set {
        health_ = value;
      }
    }

    /// <summary>Field number for the "pos_x" field.</summary>
    public const int PosXFieldNumber = 6;
    private float posX_;
    /// <summary>
    /// Fine-grained position within the chunk (floating point)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "pos_y" field.</summary>
    public const int PosYFieldNumber = 7;
    private float posY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "state_data" field.</summary>
    public const int StateDataFieldNumber = 8;
    private string stateData_ = "";
    /// <summary>
    /// Serialized state data (JSONB in DB, transmitted as a raw JSON string)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StateData {
      get { return stateData_; }
      set {
        stateData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 9;
    private long playerId_;
    /// <summary>
    /// Foreign key to Player table (Owner ID)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "world_id" field.</summary>
    public const int WorldIdFieldNumber = 10;
    private long worldId_;
    /// <summary>
    /// Foreign key to World table
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "sector_id" field.</summary>
    public const int SectorIdFieldNumber = 11;
    private long sectorId_;
    /// <summary>
    /// Foreign key to Sector table
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SectorId {
      get { return sectorId_; }
      set {
        sectorId_ = value;
      }
    }

    /// <summary>Field number for the "is_static" field.</summary>
    public const int IsStaticFieldNumber = 12;
    private bool isStatic_;
    /// <summary>
    /// Whether the entity is static/non-moving
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStatic {
      get { return isStatic_; }
      set {
        isStatic_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 13;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    /// <summary>
    /// Timestamps (OffsetDateTime)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 14;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerEntityData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerEntityData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ChunkX != other.ChunkX) return false;
      if (ChunkY != other.ChunkY) return false;
      if (EntityType != other.EntityType) return false;
      if (Health != other.Health) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosX, other.PosX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PosY, other.PosY)) return false;
      if (StateData != other.StateData) return false;
      if (PlayerId != other.PlayerId) return false;
      if (WorldId != other.WorldId) return false;
      if (SectorId != other.SectorId) return false;
      if (IsStatic != other.IsStatic) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (ChunkX != 0) hash ^= ChunkX.GetHashCode();
      if (ChunkY != 0) hash ^= ChunkY.GetHashCode();
      if (EntityType.Length != 0) hash ^= EntityType.GetHashCode();
      if (Health != 0) hash ^= Health.GetHashCode();
      if (PosX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosX);
      if (PosY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PosY);
      if (StateData.Length != 0) hash ^= StateData.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (WorldId != 0L) hash ^= WorldId.GetHashCode();
      if (SectorId != 0L) hash ^= SectorId.GetHashCode();
      if (IsStatic != false) hash ^= IsStatic.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ChunkX != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChunkX);
      }
      if (ChunkY != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ChunkY);
      }
      if (EntityType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EntityType);
      }
      if (Health != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Health);
      }
      if (PosX != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(PosY);
      }
      if (StateData.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StateData);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(SectorId);
      }
      if (IsStatic != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsStatic);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(CreatedAt);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ChunkX != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChunkX);
      }
      if (ChunkY != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ChunkY);
      }
      if (EntityType.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(EntityType);
      }
      if (Health != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Health);
      }
      if (PosX != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(PosX);
      }
      if (PosY != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(PosY);
      }
      if (StateData.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(StateData);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(SectorId);
      }
      if (IsStatic != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsStatic);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(CreatedAt);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (ChunkX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkX);
      }
      if (ChunkY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkY);
      }
      if (EntityType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityType);
      }
      if (Health != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Health);
      }
      if (PosX != 0F) {
        size += 1 + 4;
      }
      if (PosY != 0F) {
        size += 1 + 4;
      }
      if (StateData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StateData);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (WorldId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WorldId);
      }
      if (SectorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SectorId);
      }
      if (IsStatic != false) {
        size += 1 + 1;
      }
      if (createdAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (updatedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerEntityData other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.ChunkX != 0) {
        ChunkX = other.ChunkX;
      }
      if (other.ChunkY != 0) {
        ChunkY = other.ChunkY;
      }
      if (other.EntityType.Length != 0) {
        EntityType = other.EntityType;
      }
      if (other.Health != 0) {
        Health = other.Health;
      }
      if (other.PosX != 0F) {
        PosX = other.PosX;
      }
      if (other.PosY != 0F) {
        PosY = other.PosY;
      }
      if (other.StateData.Length != 0) {
        StateData = other.StateData;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.WorldId != 0L) {
        WorldId = other.WorldId;
      }
      if (other.SectorId != 0L) {
        SectorId = other.SectorId;
      }
      if (other.IsStatic != false) {
        IsStatic = other.IsStatic;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.updatedAt_ != null) {
        if (updatedAt_ == null) {
          UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdatedAt.MergeFrom(other.UpdatedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            ChunkX = input.ReadInt32();
            break;
          }
          case 24: {
            ChunkY = input.ReadInt32();
            break;
          }
          case 34: {
            EntityType = input.ReadString();
            break;
          }
          case 40: {
            Health = input.ReadInt32();
            break;
          }
          case 53: {
            PosX = input.ReadFloat();
            break;
          }
          case 61: {
            PosY = input.ReadFloat();
            break;
          }
          case 66: {
            StateData = input.ReadString();
            break;
          }
          case 72: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 80: {
            WorldId = input.ReadInt64();
            break;
          }
          case 88: {
            SectorId = input.ReadInt64();
            break;
          }
          case 96: {
            IsStatic = input.ReadBool();
            break;
          }
          case 106: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 114: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            ChunkX = input.ReadInt32();
            break;
          }
          case 24: {
            ChunkY = input.ReadInt32();
            break;
          }
          case 34: {
            EntityType = input.ReadString();
            break;
          }
          case 40: {
            Health = input.ReadInt32();
            break;
          }
          case 53: {
            PosX = input.ReadFloat();
            break;
          }
          case 61: {
            PosY = input.ReadFloat();
            break;
          }
          case 66: {
            StateData = input.ReadString();
            break;
          }
          case 72: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 80: {
            WorldId = input.ReadInt64();
            break;
          }
          case 88: {
            SectorId = input.ReadInt64();
            break;
          }
          case 96: {
            IsStatic = input.ReadBool();
            break;
          }
          case 106: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 114: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
