// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: player_entities_request_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmicScavengers.Networking.Protobuf.PlayerEntities {

  /// <summary>Holder for reflection information generated from player_entities_request_data.proto</summary>
  public static partial class PlayerEntitiesRequestDataReflection {

    #region Descriptor
    /// <summary>File descriptor for player_entities_request_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerEntitiesRequestDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJwbGF5ZXJfZW50aXRpZXNfcmVxdWVzdF9kYXRhLnByb3RvInUKGVBsYXll",
            "ckVudGl0aWVzUmVxdWVzdERhdGESEQoJcGxheWVyX2lkGAEgASgDEhAKCHdv",
            "cmxkX2lkGAIgASgDEhEKCXNlY3Rvcl9pZBgDIAEoAxIPCgdjaHVua194GAQg",
            "AygFEg8KB2NodW5rX3kYBSADKAVCbwo3Y29tLmNvc21pY3NjYXZlbmdlcnMu",
            "bmV0d29ya2luZy5wcm90b2J1Zi5wbGF5ZXJlbnRpdGllc6oCM0Nvc21pY1Nj",
            "YXZlbmdlcnMuTmV0d29ya2luZy5Qcm90b2J1Zi5QbGF5ZXJFbnRpdGllc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntitiesRequestData), global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntitiesRequestData.Parser, new[]{ "PlayerId", "WorldId", "SectorId", "ChunkX", "ChunkY" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request used by the client to ask for entities in specific chunks.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerEntitiesRequestData : pb::IMessage<PlayerEntitiesRequestData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerEntitiesRequestData> _parser = new pb::MessageParser<PlayerEntitiesRequestData>(() => new PlayerEntitiesRequestData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerEntitiesRequestData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.PlayerEntities.PlayerEntitiesRequestDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntitiesRequestData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntitiesRequestData(PlayerEntitiesRequestData other) : this() {
      playerId_ = other.playerId_;
      worldId_ = other.worldId_;
      sectorId_ = other.sectorId_;
      chunkX_ = other.chunkX_.Clone();
      chunkY_ = other.chunkY_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntitiesRequestData Clone() {
      return new PlayerEntitiesRequestData(this);
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 1;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "world_id" field.</summary>
    public const int WorldIdFieldNumber = 2;
    private long worldId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "sector_id" field.</summary>
    public const int SectorIdFieldNumber = 3;
    private long sectorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SectorId {
      get { return sectorId_; }
      set {
        sectorId_ = value;
      }
    }

    /// <summary>Field number for the "chunk_x" field.</summary>
    public const int ChunkXFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_chunkX_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> chunkX_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ChunkX {
      get { return chunkX_; }
    }

    /// <summary>Field number for the "chunk_y" field.</summary>
    public const int ChunkYFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_chunkY_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> chunkY_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ChunkY {
      get { return chunkY_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerEntitiesRequestData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerEntitiesRequestData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerId != other.PlayerId) return false;
      if (WorldId != other.WorldId) return false;
      if (SectorId != other.SectorId) return false;
      if(!chunkX_.Equals(other.chunkX_)) return false;
      if(!chunkY_.Equals(other.chunkY_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (WorldId != 0L) hash ^= WorldId.GetHashCode();
      if (SectorId != 0L) hash ^= SectorId.GetHashCode();
      hash ^= chunkX_.GetHashCode();
      hash ^= chunkY_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SectorId);
      }
      chunkX_.WriteTo(output, _repeated_chunkX_codec);
      chunkY_.WriteTo(output, _repeated_chunkY_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SectorId);
      }
      chunkX_.WriteTo(ref output, _repeated_chunkX_codec);
      chunkY_.WriteTo(ref output, _repeated_chunkY_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (WorldId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WorldId);
      }
      if (SectorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SectorId);
      }
      size += chunkX_.CalculateSize(_repeated_chunkX_codec);
      size += chunkY_.CalculateSize(_repeated_chunkY_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerEntitiesRequestData other) {
      if (other == null) {
        return;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.WorldId != 0L) {
        WorldId = other.WorldId;
      }
      if (other.SectorId != 0L) {
        SectorId = other.SectorId;
      }
      chunkX_.Add(other.chunkX_);
      chunkY_.Add(other.chunkY_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            WorldId = input.ReadInt64();
            break;
          }
          case 24: {
            SectorId = input.ReadInt64();
            break;
          }
          case 34:
          case 32: {
            chunkX_.AddEntriesFrom(input, _repeated_chunkX_codec);
            break;
          }
          case 42:
          case 40: {
            chunkY_.AddEntriesFrom(input, _repeated_chunkY_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 16: {
            WorldId = input.ReadInt64();
            break;
          }
          case 24: {
            SectorId = input.ReadInt64();
            break;
          }
          case 34:
          case 32: {
            chunkX_.AddEntriesFrom(ref input, _repeated_chunkX_codec);
            break;
          }
          case 42:
          case 40: {
            chunkY_.AddEntriesFrom(ref input, _repeated_chunkY_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
