// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entities.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmicScavengers.Networking.Protobuf.Entities {

  /// <summary>Holder for reflection information generated from entities.proto</summary>
  public static partial class EntitiesReflection {

    #region Descriptor
    /// <summary>File descriptor for entities.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntitiesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5lbnRpdGllcy5wcm90bxIaY29zbWljX3NjYXZlbmdlcnMuZW50aXRpZXMa",
            "H2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aDHRyYWl0cy5wcm90",
            "byIkChZCbHVlcHJpbnRDYXRlZ29yeVByb3RvEgoKAmlkGAEgASgJIjQKEUVu",
            "dGl0eVN0YXR1c1Byb3RvEgoKAmlkGAEgASgJEhMKC2lzX3BoeXNpY2FsGAIg",
            "ASgIIoEBChRFbnRpdHlCbHVlcHJpbnRQcm90bxIKCgJpZBgBIAEoCRITCgtj",
            "YXRlZ29yeV9pZBgCIAEoCRITCgtiYXNlX2hlYWx0aBgDIAEoBRIZChFpc19z",
            "dGF0aWNfZGVmYXVsdBgEIAEoCBIYChBiZWhhdmlvcl9jb25maWdzGAUgASgJ",
            "Ir8DChFQbGF5ZXJFbnRpdHlQcm90bxIKCgJpZBgBIAEoAxIRCglwbGF5ZXJf",
            "aWQYAiABKAMSEAoId29ybGRfaWQYAyABKAMSEQoJc2VjdG9yX2lkGAQgASgD",
            "EhQKDGJsdWVwcmludF9pZBgFIAEoCRIRCglzdGF0dXNfaWQYBiABKAkSEwoL",
            "ZW50aXR5X25hbWUYByABKAkSEQoJaXNfc3RhdGljGAggASgIEg0KBXBvc194",
            "GAkgASgQEg0KBXBvc195GAogASgQEg0KBXBvc196GAsgASgQEhAKCHJvdGF0",
            "aW9uGAwgASgCEg8KB2NodW5rX3gYDSABKAUSDwoHY2h1bmtfeRgOIAEoBRIW",
            "Cg5jdXJyZW50X2hlYWx0aBgPIAEoBRI8CgZ0cmFpdHMYECADKAsyLC5jb3Nt",
            "aWNfc2NhdmVuZ2Vycy50cmFpdHMuVHJhaXRJbnN0YW5jZVByb3RvEi4KCmNy",
            "ZWF0ZWRfYXQYESABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4K",
            "CnVwZGF0ZWRfYXQYEiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1w",
            "IucBChZFbnRpdHlNYW5pZmVzdFJlc3BvbnNlEkYKCmNhdGVnb3JpZXMYASAD",
            "KAsyMi5jb3NtaWNfc2NhdmVuZ2Vycy5lbnRpdGllcy5CbHVlcHJpbnRDYXRl",
            "Z29yeVByb3RvEj8KCHN0YXR1c2VzGAIgAygLMi0uY29zbWljX3NjYXZlbmdl",
            "cnMuZW50aXRpZXMuRW50aXR5U3RhdHVzUHJvdG8SRAoKYmx1ZXByaW50cxgD",
            "IAMoCzIwLmNvc21pY19zY2F2ZW5nZXJzLmVudGl0aWVzLkVudGl0eUJsdWVw",
            "cmludFByb3RvInoKEkVudGl0eVN5bmNSZXNwb25zZRIQCgh3b3JsZF9pZBgB",
            "IAEoAxIRCglzZWN0b3JfaWQYAiABKAMSPwoIZW50aXRpZXMYAyADKAsyLS5j",
            "b3NtaWNfc2NhdmVuZ2Vycy5lbnRpdGllcy5QbGF5ZXJFbnRpdHlQcm90b0Jl",
            "CjFjb20uY29zbWljc2NhdmVuZ2Vycy5uZXR3b3JraW5nLnByb3RvYnVmLmVu",
            "dGl0aWVzUAGqAi1Db3NtaWNTY2F2ZW5nZXJzLk5ldHdvcmtpbmcuUHJvdG9i",
            "dWYuRW50aXRpZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::CosmicScavengers.Networking.Protobuf.Traits.TraitsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto), global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto), global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto.Parser, new[]{ "Id", "IsPhysical" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto), global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto.Parser, new[]{ "Id", "CategoryId", "BaseHealth", "IsStaticDefault", "BehaviorConfigs" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto), global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto.Parser, new[]{ "Id", "PlayerId", "WorldId", "SectorId", "BlueprintId", "StatusId", "EntityName", "IsStatic", "PosX", "PosY", "PosZ", "Rotation", "ChunkX", "ChunkY", "CurrentHealth", "Traits", "CreatedAt", "UpdatedAt" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.EntityManifestResponse), global::CosmicScavengers.Networking.Protobuf.Entities.EntityManifestResponse.Parser, new[]{ "Categories", "Statuses", "Blueprints" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CosmicScavengers.Networking.Protobuf.Entities.EntitySyncResponse), global::CosmicScavengers.Networking.Protobuf.Entities.EntitySyncResponse.Parser, new[]{ "WorldId", "SectorId", "Entities" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BlueprintCategoryProto : pb::IMessage<BlueprintCategoryProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BlueprintCategoryProto> _parser = new pb::MessageParser<BlueprintCategoryProto>(() => new BlueprintCategoryProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BlueprintCategoryProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlueprintCategoryProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlueprintCategoryProto(BlueprintCategoryProto other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlueprintCategoryProto Clone() {
      return new BlueprintCategoryProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BlueprintCategoryProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BlueprintCategoryProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BlueprintCategoryProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityStatusProto : pb::IMessage<EntityStatusProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityStatusProto> _parser = new pb::MessageParser<EntityStatusProto>(() => new EntityStatusProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityStatusProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityStatusProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityStatusProto(EntityStatusProto other) : this() {
      id_ = other.id_;
      isPhysical_ = other.isPhysical_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityStatusProto Clone() {
      return new EntityStatusProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_physical" field.</summary>
    public const int IsPhysicalFieldNumber = 2;
    private bool isPhysical_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsPhysical {
      get { return isPhysical_; }
      set {
        isPhysical_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityStatusProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityStatusProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (IsPhysical != other.IsPhysical) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (IsPhysical != false) hash ^= IsPhysical.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IsPhysical != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPhysical);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IsPhysical != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsPhysical);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (IsPhysical != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityStatusProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.IsPhysical != false) {
        IsPhysical = other.IsPhysical;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            IsPhysical = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            IsPhysical = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityBlueprintProto : pb::IMessage<EntityBlueprintProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityBlueprintProto> _parser = new pb::MessageParser<EntityBlueprintProto>(() => new EntityBlueprintProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityBlueprintProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBlueprintProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBlueprintProto(EntityBlueprintProto other) : this() {
      id_ = other.id_;
      categoryId_ = other.categoryId_;
      baseHealth_ = other.baseHealth_;
      isStaticDefault_ = other.isStaticDefault_;
      behaviorConfigs_ = other.behaviorConfigs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityBlueprintProto Clone() {
      return new EntityBlueprintProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category_id" field.</summary>
    public const int CategoryIdFieldNumber = 2;
    private string categoryId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CategoryId {
      get { return categoryId_; }
      set {
        categoryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "base_health" field.</summary>
    public const int BaseHealthFieldNumber = 3;
    private int baseHealth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BaseHealth {
      get { return baseHealth_; }
      set {
        baseHealth_ = value;
      }
    }

    /// <summary>Field number for the "is_static_default" field.</summary>
    public const int IsStaticDefaultFieldNumber = 4;
    private bool isStaticDefault_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStaticDefault {
      get { return isStaticDefault_; }
      set {
        isStaticDefault_ = value;
      }
    }

    /// <summary>Field number for the "behavior_configs" field.</summary>
    public const int BehaviorConfigsFieldNumber = 5;
    private string behaviorConfigs_ = "";
    /// <summary>
    /// We store the raw JSON from YAML here for the client to parse static data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BehaviorConfigs {
      get { return behaviorConfigs_; }
      set {
        behaviorConfigs_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityBlueprintProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityBlueprintProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (CategoryId != other.CategoryId) return false;
      if (BaseHealth != other.BaseHealth) return false;
      if (IsStaticDefault != other.IsStaticDefault) return false;
      if (BehaviorConfigs != other.BehaviorConfigs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (CategoryId.Length != 0) hash ^= CategoryId.GetHashCode();
      if (BaseHealth != 0) hash ^= BaseHealth.GetHashCode();
      if (IsStaticDefault != false) hash ^= IsStaticDefault.GetHashCode();
      if (BehaviorConfigs.Length != 0) hash ^= BehaviorConfigs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CategoryId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CategoryId);
      }
      if (BaseHealth != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BaseHealth);
      }
      if (IsStaticDefault != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsStaticDefault);
      }
      if (BehaviorConfigs.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BehaviorConfigs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (CategoryId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CategoryId);
      }
      if (BaseHealth != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BaseHealth);
      }
      if (IsStaticDefault != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsStaticDefault);
      }
      if (BehaviorConfigs.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BehaviorConfigs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (CategoryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CategoryId);
      }
      if (BaseHealth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BaseHealth);
      }
      if (IsStaticDefault != false) {
        size += 1 + 1;
      }
      if (BehaviorConfigs.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BehaviorConfigs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityBlueprintProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.CategoryId.Length != 0) {
        CategoryId = other.CategoryId;
      }
      if (other.BaseHealth != 0) {
        BaseHealth = other.BaseHealth;
      }
      if (other.IsStaticDefault != false) {
        IsStaticDefault = other.IsStaticDefault;
      }
      if (other.BehaviorConfigs.Length != 0) {
        BehaviorConfigs = other.BehaviorConfigs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CategoryId = input.ReadString();
            break;
          }
          case 24: {
            BaseHealth = input.ReadInt32();
            break;
          }
          case 32: {
            IsStaticDefault = input.ReadBool();
            break;
          }
          case 42: {
            BehaviorConfigs = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            CategoryId = input.ReadString();
            break;
          }
          case 24: {
            BaseHealth = input.ReadInt32();
            break;
          }
          case 32: {
            IsStaticDefault = input.ReadBool();
            break;
          }
          case 42: {
            BehaviorConfigs = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerEntityProto : pb::IMessage<PlayerEntityProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerEntityProto> _parser = new pb::MessageParser<PlayerEntityProto>(() => new PlayerEntityProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerEntityProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityProto(PlayerEntityProto other) : this() {
      id_ = other.id_;
      playerId_ = other.playerId_;
      worldId_ = other.worldId_;
      sectorId_ = other.sectorId_;
      blueprintId_ = other.blueprintId_;
      statusId_ = other.statusId_;
      entityName_ = other.entityName_;
      isStatic_ = other.isStatic_;
      posX_ = other.posX_;
      posY_ = other.posY_;
      posZ_ = other.posZ_;
      rotation_ = other.rotation_;
      chunkX_ = other.chunkX_;
      chunkY_ = other.chunkY_;
      currentHealth_ = other.currentHealth_;
      traits_ = other.traits_.Clone();
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerEntityProto Clone() {
      return new PlayerEntityProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// ID BLOCK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "player_id" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "world_id" field.</summary>
    public const int WorldIdFieldNumber = 3;
    private long worldId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "sector_id" field.</summary>
    public const int SectorIdFieldNumber = 4;
    private long sectorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SectorId {
      get { return sectorId_; }
      set {
        sectorId_ = value;
      }
    }

    /// <summary>Field number for the "blueprint_id" field.</summary>
    public const int BlueprintIdFieldNumber = 5;
    private string blueprintId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BlueprintId {
      get { return blueprintId_; }
      set {
        blueprintId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status_id" field.</summary>
    public const int StatusIdFieldNumber = 6;
    private string statusId_ = "";
    /// <summary>
    /// IDENTITY &amp; STATUS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StatusId {
      get { return statusId_; }
      set {
        statusId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "entity_name" field.</summary>
    public const int EntityNameFieldNumber = 7;
    private string entityName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EntityName {
      get { return entityName_; }
      set {
        entityName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_static" field.</summary>
    public const int IsStaticFieldNumber = 8;
    private bool isStatic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsStatic {
      get { return isStatic_; }
      set {
        isStatic_ = value;
      }
    }

    /// <summary>Field number for the "pos_x" field.</summary>
    public const int PosXFieldNumber = 9;
    private long posX_;
    /// <summary>
    /// SPATIAL DATA (Deterministic scaled longs)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PosX {
      get { return posX_; }
      set {
        posX_ = value;
      }
    }

    /// <summary>Field number for the "pos_y" field.</summary>
    public const int PosYFieldNumber = 10;
    private long posY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PosY {
      get { return posY_; }
      set {
        posY_ = value;
      }
    }

    /// <summary>Field number for the "pos_z" field.</summary>
    public const int PosZFieldNumber = 11;
    private long posZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PosZ {
      get { return posZ_; }
      set {
        posZ_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 12;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    /// <summary>Field number for the "chunk_x" field.</summary>
    public const int ChunkXFieldNumber = 13;
    private int chunkX_;
    /// <summary>
    /// COMPUTED SPATIAL
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkX {
      get { return chunkX_; }
      set {
        chunkX_ = value;
      }
    }

    /// <summary>Field number for the "chunk_y" field.</summary>
    public const int ChunkYFieldNumber = 14;
    private int chunkY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkY {
      get { return chunkY_; }
      set {
        chunkY_ = value;
      }
    }

    /// <summary>Field number for the "current_health" field.</summary>
    public const int CurrentHealthFieldNumber = 15;
    private int currentHealth_;
    /// <summary>
    /// LIVE STATS
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrentHealth {
      get { return currentHealth_; }
      set {
        currentHealth_ = value;
      }
    }

    /// <summary>Field number for the "traits" field.</summary>
    public const int TraitsFieldNumber = 16;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> _repeated_traits_codec
        = pb::FieldCodec.ForMessage(130, global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> traits_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto>();
    /// <summary>
    /// STRUCTURED TRAITS DATA
    /// We use the types defined in traits.proto here
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Traits.TraitInstanceProto> Traits {
      get { return traits_; }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 17;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    /// <summary>
    /// SYSTEM METADATA
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 18;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerEntityProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerEntityProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (PlayerId != other.PlayerId) return false;
      if (WorldId != other.WorldId) return false;
      if (SectorId != other.SectorId) return false;
      if (BlueprintId != other.BlueprintId) return false;
      if (StatusId != other.StatusId) return false;
      if (EntityName != other.EntityName) return false;
      if (IsStatic != other.IsStatic) return false;
      if (PosX != other.PosX) return false;
      if (PosY != other.PosY) return false;
      if (PosZ != other.PosZ) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
      if (ChunkX != other.ChunkX) return false;
      if (ChunkY != other.ChunkY) return false;
      if (CurrentHealth != other.CurrentHealth) return false;
      if(!traits_.Equals(other.traits_)) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (WorldId != 0L) hash ^= WorldId.GetHashCode();
      if (SectorId != 0L) hash ^= SectorId.GetHashCode();
      if (BlueprintId.Length != 0) hash ^= BlueprintId.GetHashCode();
      if (StatusId.Length != 0) hash ^= StatusId.GetHashCode();
      if (EntityName.Length != 0) hash ^= EntityName.GetHashCode();
      if (IsStatic != false) hash ^= IsStatic.GetHashCode();
      if (PosX != 0L) hash ^= PosX.GetHashCode();
      if (PosY != 0L) hash ^= PosY.GetHashCode();
      if (PosZ != 0L) hash ^= PosZ.GetHashCode();
      if (Rotation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
      if (ChunkX != 0) hash ^= ChunkX.GetHashCode();
      if (ChunkY != 0) hash ^= ChunkY.GetHashCode();
      if (CurrentHealth != 0) hash ^= CurrentHealth.GetHashCode();
      hash ^= traits_.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SectorId);
      }
      if (BlueprintId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BlueprintId);
      }
      if (StatusId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StatusId);
      }
      if (EntityName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(EntityName);
      }
      if (IsStatic != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsStatic);
      }
      if (PosX != 0L) {
        output.WriteRawTag(73);
        output.WriteSFixed64(PosX);
      }
      if (PosY != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(PosY);
      }
      if (PosZ != 0L) {
        output.WriteRawTag(89);
        output.WriteSFixed64(PosZ);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(Rotation);
      }
      if (ChunkX != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(ChunkX);
      }
      if (ChunkY != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(ChunkY);
      }
      if (CurrentHealth != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(CurrentHealth);
      }
      traits_.WriteTo(output, _repeated_traits_codec);
      if (createdAt_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(CreatedAt);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (WorldId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(SectorId);
      }
      if (BlueprintId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BlueprintId);
      }
      if (StatusId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StatusId);
      }
      if (EntityName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(EntityName);
      }
      if (IsStatic != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsStatic);
      }
      if (PosX != 0L) {
        output.WriteRawTag(73);
        output.WriteSFixed64(PosX);
      }
      if (PosY != 0L) {
        output.WriteRawTag(81);
        output.WriteSFixed64(PosY);
      }
      if (PosZ != 0L) {
        output.WriteRawTag(89);
        output.WriteSFixed64(PosZ);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(101);
        output.WriteFloat(Rotation);
      }
      if (ChunkX != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(ChunkX);
      }
      if (ChunkY != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(ChunkY);
      }
      if (CurrentHealth != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(CurrentHealth);
      }
      traits_.WriteTo(ref output, _repeated_traits_codec);
      if (createdAt_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(CreatedAt);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(146, 1);
        output.WriteMessage(UpdatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (WorldId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WorldId);
      }
      if (SectorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SectorId);
      }
      if (BlueprintId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BlueprintId);
      }
      if (StatusId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StatusId);
      }
      if (EntityName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntityName);
      }
      if (IsStatic != false) {
        size += 1 + 1;
      }
      if (PosX != 0L) {
        size += 1 + 8;
      }
      if (PosY != 0L) {
        size += 1 + 8;
      }
      if (PosZ != 0L) {
        size += 1 + 8;
      }
      if (Rotation != 0F) {
        size += 1 + 4;
      }
      if (ChunkX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkX);
      }
      if (ChunkY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkY);
      }
      if (CurrentHealth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentHealth);
      }
      size += traits_.CalculateSize(_repeated_traits_codec);
      if (createdAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (updatedAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerEntityProto other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.WorldId != 0L) {
        WorldId = other.WorldId;
      }
      if (other.SectorId != 0L) {
        SectorId = other.SectorId;
      }
      if (other.BlueprintId.Length != 0) {
        BlueprintId = other.BlueprintId;
      }
      if (other.StatusId.Length != 0) {
        StatusId = other.StatusId;
      }
      if (other.EntityName.Length != 0) {
        EntityName = other.EntityName;
      }
      if (other.IsStatic != false) {
        IsStatic = other.IsStatic;
      }
      if (other.PosX != 0L) {
        PosX = other.PosX;
      }
      if (other.PosY != 0L) {
        PosY = other.PosY;
      }
      if (other.PosZ != 0L) {
        PosZ = other.PosZ;
      }
      if (other.Rotation != 0F) {
        Rotation = other.Rotation;
      }
      if (other.ChunkX != 0) {
        ChunkX = other.ChunkX;
      }
      if (other.ChunkY != 0) {
        ChunkY = other.ChunkY;
      }
      if (other.CurrentHealth != 0) {
        CurrentHealth = other.CurrentHealth;
      }
      traits_.Add(other.traits_);
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.updatedAt_ != null) {
        if (updatedAt_ == null) {
          UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdatedAt.MergeFrom(other.UpdatedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            WorldId = input.ReadInt64();
            break;
          }
          case 32: {
            SectorId = input.ReadInt64();
            break;
          }
          case 42: {
            BlueprintId = input.ReadString();
            break;
          }
          case 50: {
            StatusId = input.ReadString();
            break;
          }
          case 58: {
            EntityName = input.ReadString();
            break;
          }
          case 64: {
            IsStatic = input.ReadBool();
            break;
          }
          case 73: {
            PosX = input.ReadSFixed64();
            break;
          }
          case 81: {
            PosY = input.ReadSFixed64();
            break;
          }
          case 89: {
            PosZ = input.ReadSFixed64();
            break;
          }
          case 101: {
            Rotation = input.ReadFloat();
            break;
          }
          case 104: {
            ChunkX = input.ReadInt32();
            break;
          }
          case 112: {
            ChunkY = input.ReadInt32();
            break;
          }
          case 120: {
            CurrentHealth = input.ReadInt32();
            break;
          }
          case 130: {
            traits_.AddEntriesFrom(input, _repeated_traits_codec);
            break;
          }
          case 138: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 146: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            WorldId = input.ReadInt64();
            break;
          }
          case 32: {
            SectorId = input.ReadInt64();
            break;
          }
          case 42: {
            BlueprintId = input.ReadString();
            break;
          }
          case 50: {
            StatusId = input.ReadString();
            break;
          }
          case 58: {
            EntityName = input.ReadString();
            break;
          }
          case 64: {
            IsStatic = input.ReadBool();
            break;
          }
          case 73: {
            PosX = input.ReadSFixed64();
            break;
          }
          case 81: {
            PosY = input.ReadSFixed64();
            break;
          }
          case 89: {
            PosZ = input.ReadSFixed64();
            break;
          }
          case 101: {
            Rotation = input.ReadFloat();
            break;
          }
          case 104: {
            ChunkX = input.ReadInt32();
            break;
          }
          case 112: {
            ChunkY = input.ReadInt32();
            break;
          }
          case 120: {
            CurrentHealth = input.ReadInt32();
            break;
          }
          case 130: {
            traits_.AddEntriesFrom(ref input, _repeated_traits_codec);
            break;
          }
          case 138: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 146: {
            if (updatedAt_ == null) {
              UpdatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdatedAt);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntityManifestResponse : pb::IMessage<EntityManifestResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityManifestResponse> _parser = new pb::MessageParser<EntityManifestResponse>(() => new EntityManifestResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityManifestResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityManifestResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityManifestResponse(EntityManifestResponse other) : this() {
      categories_ = other.categories_.Clone();
      statuses_ = other.statuses_.Clone();
      blueprints_ = other.blueprints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityManifestResponse Clone() {
      return new EntityManifestResponse(this);
    }

    /// <summary>Field number for the "categories" field.</summary>
    public const int CategoriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto> _repeated_categories_codec
        = pb::FieldCodec.ForMessage(10, global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto> categories_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.BlueprintCategoryProto> Categories {
      get { return categories_; }
    }

    /// <summary>Field number for the "statuses" field.</summary>
    public const int StatusesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto> _repeated_statuses_codec
        = pb::FieldCodec.ForMessage(18, global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto> statuses_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityStatusProto> Statuses {
      get { return statuses_; }
    }

    /// <summary>Field number for the "blueprints" field.</summary>
    public const int BlueprintsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto> _repeated_blueprints_codec
        = pb::FieldCodec.ForMessage(26, global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto> blueprints_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.EntityBlueprintProto> Blueprints {
      get { return blueprints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityManifestResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityManifestResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!categories_.Equals(other.categories_)) return false;
      if(!statuses_.Equals(other.statuses_)) return false;
      if(!blueprints_.Equals(other.blueprints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= categories_.GetHashCode();
      hash ^= statuses_.GetHashCode();
      hash ^= blueprints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      categories_.WriteTo(output, _repeated_categories_codec);
      statuses_.WriteTo(output, _repeated_statuses_codec);
      blueprints_.WriteTo(output, _repeated_blueprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      categories_.WriteTo(ref output, _repeated_categories_codec);
      statuses_.WriteTo(ref output, _repeated_statuses_codec);
      blueprints_.WriteTo(ref output, _repeated_blueprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += categories_.CalculateSize(_repeated_categories_codec);
      size += statuses_.CalculateSize(_repeated_statuses_codec);
      size += blueprints_.CalculateSize(_repeated_blueprints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityManifestResponse other) {
      if (other == null) {
        return;
      }
      categories_.Add(other.categories_);
      statuses_.Add(other.statuses_);
      blueprints_.Add(other.blueprints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            categories_.AddEntriesFrom(input, _repeated_categories_codec);
            break;
          }
          case 18: {
            statuses_.AddEntriesFrom(input, _repeated_statuses_codec);
            break;
          }
          case 26: {
            blueprints_.AddEntriesFrom(input, _repeated_blueprints_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            categories_.AddEntriesFrom(ref input, _repeated_categories_codec);
            break;
          }
          case 18: {
            statuses_.AddEntriesFrom(ref input, _repeated_statuses_codec);
            break;
          }
          case 26: {
            blueprints_.AddEntriesFrom(ref input, _repeated_blueprints_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EntitySyncResponse : pb::IMessage<EntitySyncResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntitySyncResponse> _parser = new pb::MessageParser<EntitySyncResponse>(() => new EntitySyncResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntitySyncResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CosmicScavengers.Networking.Protobuf.Entities.EntitiesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySyncResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySyncResponse(EntitySyncResponse other) : this() {
      worldId_ = other.worldId_;
      sectorId_ = other.sectorId_;
      entities_ = other.entities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntitySyncResponse Clone() {
      return new EntitySyncResponse(this);
    }

    /// <summary>Field number for the "world_id" field.</summary>
    public const int WorldIdFieldNumber = 1;
    private long worldId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long WorldId {
      get { return worldId_; }
      set {
        worldId_ = value;
      }
    }

    /// <summary>Field number for the "sector_id" field.</summary>
    public const int SectorIdFieldNumber = 2;
    private long sectorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SectorId {
      get { return sectorId_; }
      set {
        sectorId_ = value;
      }
    }

    /// <summary>Field number for the "entities" field.</summary>
    public const int EntitiesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto> _repeated_entities_codec
        = pb::FieldCodec.ForMessage(26, global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto.Parser);
    private readonly pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto> entities_ = new pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CosmicScavengers.Networking.Protobuf.Entities.PlayerEntityProto> Entities {
      get { return entities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntitySyncResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntitySyncResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorldId != other.WorldId) return false;
      if (SectorId != other.SectorId) return false;
      if(!entities_.Equals(other.entities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorldId != 0L) hash ^= WorldId.GetHashCode();
      if (SectorId != 0L) hash ^= SectorId.GetHashCode();
      hash ^= entities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorldId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SectorId);
      }
      entities_.WriteTo(output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorldId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(WorldId);
      }
      if (SectorId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SectorId);
      }
      entities_.WriteTo(ref output, _repeated_entities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorldId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(WorldId);
      }
      if (SectorId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SectorId);
      }
      size += entities_.CalculateSize(_repeated_entities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntitySyncResponse other) {
      if (other == null) {
        return;
      }
      if (other.WorldId != 0L) {
        WorldId = other.WorldId;
      }
      if (other.SectorId != 0L) {
        SectorId = other.SectorId;
      }
      entities_.Add(other.entities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WorldId = input.ReadInt64();
            break;
          }
          case 16: {
            SectorId = input.ReadInt64();
            break;
          }
          case 26: {
            entities_.AddEntriesFrom(input, _repeated_entities_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WorldId = input.ReadInt64();
            break;
          }
          case 16: {
            SectorId = input.ReadInt64();
            break;
          }
          case 26: {
            entities_.AddEntriesFrom(ref input, _repeated_entities_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
